version: 2
jobs:
    build:
        working_directory: ~/project
        docker:
            - image: 'circleci/node:10'
            
        steps:
            - checkout
            - restore_cache:
                keys:
                    - 'v1-dependencies-{{ checksum "package.json" }}'
                    - v1-dependencies-
            - run: 'npm install'
            - save_cache:
                paths:
                    - node_modules
                    - dist
                key: 'v1-dependencies-{{ checksum "package.json" }}'

